## Hello Jupyter

In [2]:
print ('hello Alex')

hello Alex


In [3]:
x = 3
print (x)

3


In [4]:
# reexecute this cell several times
x = x + 5
# output of the last line in the cell is shown
x

8

In [5]:
my_string = "string can contain characters including \n new lines and \t tabs"
my_string

'string can contain characters including \n new lines and \t tabs'

In [6]:
print (my_string)

string can contain characters including 
 new lines and 	 tabs


In [7]:
12 + 45

57

In [8]:
# result types are safer
24 * 3.5

84.0

## Lists, Dictionaries

In [9]:
x = [1, 2, 3]

In [10]:
# in python enumeration starts from 0
x[0], x[2]

(1, 3)

In [11]:
y = x[0:2] + [5, 10]
y

[1, 2, 5, 10]

In [12]:
y[::2]

[1, 5]

In [13]:
y[::-1]

[10, 5, 2, 1]

## Dictionaries

In [14]:
d = {'a': 1, 'b': 2}

In [15]:
d['c'] = 3
d['casdsd'] = 34
d

{'a': 1, 'b': 2, 'c': 3, 'casdsd': 34}

In [16]:
for key, value in d.items():
    print (key, value)

a 1
b 2
c 3
casdsd 34


## Important python libraries

 - numpy (numerics) + scipy (scientific functions) 
 - matplotlib - plotting
 - pandas - convenient operations on data for Data Science
 - scikit-learn - machine learning
 
We'll meet them very soon.

## Hello numpy!

`numpy` is the core of scientific python. It is the most convenient way to organize number-crunching in python.

In [17]:
import numpy

In [18]:
x = numpy.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
x.reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [20]:
# x.reshape(3, 4)

In [21]:
# slicing has the same logic for lists / strings / tuples / numpy, etc
x[:4]

array([0, 1, 2, 3])

In [22]:
print (x[:3])
print (x[3:7])
print (x[7:])

[0 1 2]
[3 4 5 6]
[7 8 9]


### Vector operations

In [23]:
x = numpy.arange(10 ** 6) #Return evenly spaced values within a given interval.
# vector operations do similar task for each element. In this case each element is multiplied by 3 and 12 added.
3 * x + 12.

array([1.200000e+01, 1.500000e+01, 1.800000e+01, ..., 3.000003e+06,
       3.000006e+06, 3.000009e+06])

In [24]:
# use timing magic to understand this is quite fast
%timeit 3 * x + 12.

1.94 ms ± 127 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [25]:
Z = numpy.arange(15).reshape(5, 3)
Z

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [26]:
numpy.log(numpy.exp(Z)) # type conversion happened

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.]])

In [27]:
Z += 4

In [28]:
Z

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [29]:
Z[::2, :]

array([[ 4,  5,  6],
       [10, 11, 12],
       [16, 17, 18]])

In [30]:
Z[[0, 2, 4], :]

array([[ 4,  5,  6],
       [10, 11, 12],
       [16, 17, 18]])

In [31]:
Z.sum(axis=1)

array([15, 24, 33, 42, 51])

In [91]:
# axes are also zero-numerated
Z.sum(axis=0)

array([50, 55, 60])

In [33]:
Z.max(axis=1)

array([ 6,  9, 12, 15, 18])

In [34]:
Z2 = - Z
Z2 = numpy.sort(Z2, axis=1)
Z2

array([[ -6,  -5,  -4],
       [ -9,  -8,  -7],
       [-12, -11, -10],
       [-15, -14, -13],
       [-18, -17, -16]])

## Indexing with boolean array

In [35]:
x = numpy.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
x > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [37]:
x[x < 7.4]

array([0, 1, 2, 3, 4, 5, 6, 7])

## Copies

Many operations in numpy don't create copies, but operate with the same memory 

In [38]:
x = numpy.arange(10)
y = x[:5]

print (x, y)
y[0] = 10
print (x, y)

[0 1 2 3 4 5 6 7 8 9] [0 1 2 3 4]
[10  1  2  3  4  5  6  7  8  9] [10  1  2  3  4]


this happened because x and y point __to the same place in memory__

In [39]:
x = numpy.arange(10)
y = x[:5].copy()
print (x, y)
y[0] = 10
print (x, y)

[0 1 2 3 4 5 6 7 8 9] [0 1 2 3 4]
[0 1 2 3 4 5 6 7 8 9] [10  1  2  3  4]


## Random numbers

module `numpy.random` helps with generating random numbers

In [40]:
# generating 10000 random numbers at once
numpy.random.normal(loc=2, scale=12, size=10000)

array([-20.89969022,   5.57937927,  -1.93837472, ...,  -6.76650755,
        10.70382615,  -1.91988666])

## Sorting

In [41]:
x = numpy.random.random(size=1000)
x = numpy.sort(x)

In [42]:
print (x[:10])
print (x[-10:])

[0.00072198 0.00263484 0.00315437 0.00322942 0.00480214 0.0089279
 0.00988581 0.00995463 0.01113102 0.01345223]
[0.9892928  0.99357342 0.99497685 0.9950139  0.99507408 0.99635771
 0.9969055  0.99738762 0.99956326 0.99981949]


## Arg...

arg-functions allow writing non-trivial operations with a couple of lines

In [43]:
# random.random generates uniform in [0, 1]
random_numbers = numpy.random.random(size=1000)
indices = numpy.argsort(random_numbers) #Returns the indices that would sort an array.

In [44]:
numpy.alltrue(random_numbers[indices] == numpy.sort(random_numbers)) #Test whether all array elements along a given axis evaluate to True.

True

In [45]:
indices[:10]

array([963, 115, 500, 574, 430, 750, 454, 342, 101, 566])

In [46]:
random_numbers.min(), random_numbers.max()

(0.000742001773116785, 0.9998949185299909)

In [47]:
random_numbers.argmax(), random_numbers[random_numbers.argmax()]

(484, 0.9998949185299909)

In [48]:
random_numbers.argmin(), random_numbers[random_numbers.argmin()]

(963, 0.000742001773116785)

## Homework 3

In [49]:
import numpy


In [86]:
x = numpy.random.normal(loc=2, scale=12, size=1000)
x

array([-1.35878328e+01, -3.29334768e+00,  1.47053920e+01, -2.28116586e+01,
       -4.08786933e+00,  1.25959905e+01,  4.60716802e+00, -1.24095533e+00,
        4.72564697e-01,  1.35779749e+01,  2.30048333e+01,  6.80574016e+00,
        1.90241422e+01,  1.18966656e+01, -1.67280550e+00, -1.50787746e+01,
       -2.81444886e+00, -4.83808262e+00,  5.49415612e+00,  2.69096719e+00,
        2.45950193e+01,  4.68278984e-01, -4.46881070e+00,  1.74992061e+00,
       -8.04263666e+00,  8.31434605e+00, -1.36053585e+00,  7.33284113e+00,
       -1.18069646e+01,  2.18632298e+01,  3.78622537e+00,  5.38128165e+00,
       -8.46181170e+00, -2.58272685e+00, -2.11936499e+00, -4.15814004e+00,
       -2.10204074e-02,  7.68070517e+00,  1.77366913e+01, -1.04385275e+01,
       -3.89619546e+00,  1.22944224e+00, -1.43310899e+01,  1.59458952e+01,
        5.23954904e+00, -1.54425992e+01,  1.10874717e+01,  1.31046825e+01,
        3.49822978e+00,  9.03201992e+00, -1.45124158e+01, -5.07080336e+00,
        6.64625409e+00,  

In [90]:
x[x>0.0]



array([1.47053920e+01, 1.25959905e+01, 4.60716802e+00, 4.72564697e-01,
       1.35779749e+01, 2.30048333e+01, 6.80574016e+00, 1.90241422e+01,
       1.18966656e+01, 5.49415612e+00, 2.69096719e+00, 2.45950193e+01,
       4.68278984e-01, 1.74992061e+00, 8.31434605e+00, 7.33284113e+00,
       2.18632298e+01, 3.78622537e+00, 5.38128165e+00, 7.68070517e+00,
       1.77366913e+01, 1.22944224e+00, 1.59458952e+01, 5.23954904e+00,
       1.10874717e+01, 1.31046825e+01, 3.49822978e+00, 9.03201992e+00,
       6.64625409e+00, 1.77279810e+01, 4.50881008e+00, 4.26210965e+00,
       2.98535132e+00, 1.30667369e+01, 4.82730556e+00, 1.39501279e+01,
       2.67368450e-01, 9.47849765e+00, 5.91616523e+00, 5.85432432e+00,
       1.63296381e+00, 3.87282610e+00, 1.14880825e+01, 1.21883847e+01,
       2.17863766e+00, 1.90202502e+01, 1.16044880e+01, 3.76235807e+00,
       4.72595350e+00, 7.50773768e+00, 4.67508663e+00, 2.30492453e+01,
       1.06211822e+01, 6.30345502e+00, 3.29951521e+00, 2.15542980e-02,
      

In [106]:

len(x[x<2]), max(x[x<2]), min(x[x<2]), numpy.mean(x[x<2]), numpy.std(x[x<2])



(475,
 1.9425538144787944,
 -40.36783941191803,
 -7.6493606198532484,
 7.373774210392715)

## References:
* `numpy` documentation: https://docs.scipy.org/doc/numpy/reference/
    * almost any question about `numpy` is already answered on stackoverflow
* [From python to numpy: a beautiful book about numpy](https://github.com/rougier/from-python-to-numpy)
* Data manipulation with `numpy`: tips and tricks [part1](http://arogozhnikov.github.io/2015/09/29/NumpyTipsAndTricks1.html), [part2](http://arogozhnikov.github.io/2015/09/30/NumpyTipsAndTricks2.html)
